# Conda environment file for Fractal Dimension Analysis Tool
# Use: conda env create -f environment.yml
# Activate: conda activate fractal-analysis

name: fractal-analysis
channels:
  - conda-forge
  - defaults

dependencies:
  # Python version
  - python>=3.8,<3.12
  
  # Core scientific computing (required)
  - numpy>=1.21.0
  - scipy>=1.7.0
  - matplotlib>=3.5.0
  - numba>=0.56.0
  
  # Optional analysis tools
  - pandas>=1.3.0
  - seaborn>=0.11.0
  - h5py>=3.0.0
  
  # Development and testing (optional)
  - pytest>=6.0.0
  - jupyter>=1.0.0
  
  # Documentation and code quality
  - black
  - flake8
  
  # pip-only packages (if any)
  - pip
  - pip:
    # Add any PyPI-only packages here if needed
    # - some-package-not-on-conda

# Environment variables (optional)
variables:
  # Optimize numba performance
  NUMBA_CACHE_DIR: $HOME/.numba_cache
  # Set matplotlib backend for headless systems
  MPLBACKEND: Agg
